export default [
	"<section id=\"lIBq7Ire6\" type=\"text\"><p>Home</p></section>",
	"<section id=\"wiO6_AVpDu\" type=\"text\"><p style=\"text-align: center;\">Shop</p></section>",
	"<section id=\"1kt-fkeMAK\" type=\"text\"><p style=\"text-align: center;\">Site</p></section>",
	"<section id=\"6287u3TQVu\" type=\"text\"><p style=\"text-align: center;\">Chat</p></section>",
	"<section id=\"KdRj3P5VJzc\" type=\"text\"><p style=\"text-align: center;\"><strong>Our Portfolio</strong></p></section>",
	"<section id=\"60-OPIRcR49\" type=\"text\"><p style=\"text-align: center;\">PERFECTLY SIMPLE DESIGN</p></section>",
	"<section id=\"2AHhADq2t\" type=\"text\"><p><strong>Professional</strong></p></section>",
	"<section id=\"k-fX1atyU\" type=\"text\"><p>STRATEGY TEAM</p></section>",
	"<section id=\"G6hw1u_xa\" type=\"text\"><p>Fusce maximus nunc ut quam aliquet, cursus tempus justo tincidunt. Vivamus quis magna molestie, pellentesque tellus ac, efficitur nibh,&nbsp;cursus tempus justo tincidunt.</p></section>",
	"<section id=\"1TrE5CYuV\" type=\"button\"><p>Details</p></section>",
	"<section id=\"BO2hU5VzcI\" type=\"text\"><p><strong>Welcome to my Customers!</strong></p></section>",
	"<section id=\"G3i_ontanE\" type=\"text\"><p>10-15. Joey Barch</p></section>",
	"<section id=\"TuAiS7jSBI\" type=\"text\"><p>Sed et lacus volutpat, consectetur erat vel, aliquet mauris. Praesent nisi elit, molestie sit amet ante ut, consectetur condimentum elit. Aliquam erat volutpat. Aenean nec congue est. Aliquam erat volutpat. Ut in feugiat est. Quisque libero tellus, volutpat non dapibus vitae, feugiat quis nisl.</p></section>",
	"<section id=\"rn5lr5NNrN\" type=\"button\"><p>Read Now</p></section>",
	"<section id=\"UhlM1UHNLW\" type=\"text\"><p style=\"text-align: center;\"><strong>Professional</strong></p></section>",
	"<section id=\"d-CZCx-OWv\" type=\"text\"><p style=\"text-align: center;\">STRATEGY TEAM</p></section>",
	"<section id=\"-5EX_YNIcx\" type=\"text\"><p>Fusce maximus nunc ut quam aliquet, cursus tempus justo tincidunt. Vivamus quis magna molestie, pellentesque tellus ac, efficitur nibh,&nbsp;cursus tempus justo tincidunt.</p></section>",
	"<section id=\"GAOcGJo9u\" type=\"button\"><p>Shop Now</p></section>",
	"<section id=\"ahJjh4-AS\" type=\"text\"><p><strong>Our Team</strong></p></section>",
	"<section id=\"bl7UAtOYe\" type=\"text\"><p>MEET WITH</p></section>",
	"<section id=\"9c0_LzTtC\" type=\"text\"><p><strong>Vivamus accumsan erat id tortor ornare euismod.</strong><br><br>Nullam enim libero. Cras non magna sit amet massa aliquam suscipit.</p></section>",
	"<section id=\"Cy0EjuLkf\" type=\"text\"><p>Aenean ac finibus dui, non eleifend ligula. Nulla facilisi. Aligue condim. <strong>Sed suscipit metus ligula!</strong></p></section>",
	"<section id=\"v0lUz7EZ7\" type=\"button\"><p>Shop Now</p></section>",
	"<section id=\"5DucigUVy\" type=\"text\"><p style=\"text-align: center;\">Style, Fast, Mission</p></section>",
	"<section id=\"8I9Hc45I5n\" type=\"text\"><p style=\"text-align: center;\">Style, Fast, Mission</p></section>",
	"<section id=\"bIBBZQ9Ksf\" type=\"text\"><p style=\"text-align: center;\">Style, Fast, Mission</p></section>",
	"<section id=\"wR6qFZ1Jld\" type=\"text\"><p style=\"text-align: center;\">Style, Fast, Mission</p></section>",
	"<section id=\"KdrQAZQGFk\" type=\"text\"><p style=\"text-align: center;\"><strong>Services we provide</strong></p></section>",
	"<section id=\"tFyeP6HSI\" type=\"text\"><p style=\"text-align: center;\">LET&#39;S START WITH US!</p></section>",
	"<section id=\"S59DpNVhHs\" type=\"text\"><p style=\"text-align: center;\"><strong>Jim Carry, Phd. -&nbsp;FOUNDER</strong></p></section>",
	"<section id=\"pw4nn1lZ4q\" type=\"text\"><p style=\"text-align: center;\">FOUNDER</p></section>",
	"<section id=\"ztrWNjrt1p\" type=\"text\"><p style=\"text-align: center;\"><strong>Jim Carry, Phd. -&nbsp;FOUNDER</strong></p></section>",
	"<section id=\"hyc0OQk3TG\" type=\"text\"><p style=\"text-align: center;\">FOUNDER</p></section>",
	"<section id=\"LNqn53Y40O\" type=\"text\"><p style=\"text-align: center;\"><b>Light</b></p></section>",
	"<section id=\"1sWBuKdw_V\" type=\"text\"><p style=\"text-align: center;\">Their Pronunciation and their most common words.</p></section>",
	"<section id=\"DspJSEDO94\" type=\"text\"><p style=\"text-align: center;\"><strong>$16.00</strong></p></section>",
	"<section id=\"AOW7_PU8FA\" type=\"button\"><p>Shop Now</p></section>",
	"<section id=\"rMAQtiQATg\" type=\"text\"><p style=\"text-align: center;\"><b>Medium</b></p></section>",
	"<section id=\"U2bTZqZGBc\" type=\"text\"><p style=\"text-align: center;\">Their Pronunciation and their most common words.</p></section>",
	"<section id=\"87uACi154kk\" type=\"text\"><p style=\"text-align: center;\"><strong>$16.00</strong></p></section>",
	"<section id=\"iGCjdAHNPc1\" type=\"button\"><p>Shop Now</p></section>",
	"<section id=\"4hFdp3DDrxG\" type=\"text\"><p style=\"text-align: center;\"><b>Strong</b></p></section>",
	"<section id=\"CrSorptBYOs\" type=\"text\"><p style=\"text-align: center;\">Their Pronunciation and their most common words.</p></section>",
	"<section id=\"SEsswitxOXt\" type=\"text\"><p style=\"text-align: center;\"><strong>$16.00</strong></p></section>",
	"<section id=\"aNuzXF3O05C\" type=\"button\"><p>Shop Now</p></section>",
	"<section id=\"6nfRRJyOW\" type=\"text\"><p style=\"text-align: center;\">THEIR PRONUNCIATION AND THEIR MOST COMMON WORDS.</p></section>",
];
