export default {
	body: {
		eid: "root",
		type: "body",
		children: [
			{
				eid: "TU5iJhJ4nI",
				type: "fullwidth",
				children: [
					{
						eid: "rrJ2vE_XsK",
						type: "box",
						children: [
							{
								eid: "zmitKgUA2",
								type: "box",
								children: [
									{
										eid: "5hHiyQ2Atj",
										type: "box",
										children: [
											{
												attrs: {
													text: "<p>Button</p>\n",
													sizeType: "FIT_TO_TEXT",
													href: "https://chamaileon.io/?x=хамелеон",
													fullWidthOnMobile: true,
													align: "center",
												},
												style: {
													"line-height": "25px",
													color: "white",
													"font-size": "18px",
													"font-family": "Arial",
													"letter-spacing": "normal",
													"background-color": "blue",
													"background-repeat": "no-repeat",
													"background-position": "center center",
													"background-image": "url()",
													"border-radius": "5px",
													"border-left-color": "#000000",
													"border-left-style": "solid",
													"border-left-width": "0px",
													"border-bottom-color": "#000000",
													"border-bottom-style": "solid",
													"border-bottom-width": "0px",
													"border-right-color": "#000000",
													"border-right-style": "solid",
													"border-right-width": "0px",
													"border-top-color": "#000000",
													"border-top-style": "solid",
													"border-top-width": "0px",
													"margin-left": "20px",
													"margin-bottom": "20px",
													"margin-right": "20px",
													"margin-top": "20px",
													"padding-left": "15px",
													"padding-bottom": "15px",
													"padding-right": "15px",
													"padding-top": "15px",
												},
												type: "button",
												eid: "_WSDj6Sw6",
											},
										],
										attrs: {},
										style: {
											"background-color": "",
											"background-position": "top center",
											"background-repeat": "no-repeat",
											"background-image": "url()",
											"border-top-color": "",
											"border-top-style": "solid",
											"border-top-width": "0px",
											"border-right-color": "",
											"border-right-style": "solid",
											"border-right-width": "0px",
											"border-bottom-color": "",
											"border-bottom-style": "solid",
											"border-bottom-width": "0px",
											"border-left-color": "",
											"border-left-style": "solid",
											"border-left-width": "0px",
											"margin-left": "0px",
											"margin-bottom": "0px",
											"margin-right": "0px",
											"margin-top": "0px",
											"padding-left": "0px",
											"padding-bottom": "0px",
											"padding-right": "0px",
											"padding-top": "0px",
										},
									},
								],
								attrs: { hideOnMobile: false, hideOnDesktop: false },
								style: {
									"background-color": "",
									"background-repeat": "no-repeat",
									"background-position": "center center",
									"background-image": "url()",
									"border-radius": "0px",
									"border-left-color": "#000000",
									"border-left-style": "solid",
									"border-left-width": "0px",
									"border-bottom-color": "#000000",
									"border-bottom-style": "solid",
									"border-bottom-width": "0px",
									"border-right-color": "#000000",
									"border-right-style": "solid",
									"border-right-width": "0px",
									"border-top-color": "#000000",
									"border-top-style": "solid",
									"border-top-width": "0px",
									"margin-left": "0px",
									"margin-bottom": "0px",
									"margin-right": "0px",
									"margin-top": "0px",
									"padding-left": "0px",
									"padding-bottom": "0px",
									"padding-right": "0px",
									"padding-top": "0px",
								},
							},
						],
						attrs: {},
						style: {
							"background-color": "",
							"background-position": "center center",
							"background-repeat": "no-repeat",
							"background-image":
								"url(https://images.chamaileon.io/5faa7158ec61f57ca4b9be7e/5faa7158ec61f52f03b9be88/1607087407646_1607087405728_mav-header.jpg)",
							"border-top-color": "",
							"border-top-style": "solid",
							"border-top-width": "0px",
							"border-right-color": "",
							"border-right-style": "solid",
							"border-right-width": "0px",
							"border-bottom-color": "",
							"border-bottom-style": "solid",
							"border-bottom-width": "0px",
							"border-left-color": "",
							"border-left-style": "solid",
							"border-left-width": "0px",
							"margin-left": "0px",
							"margin-bottom": "16px",
							"margin-right": "16px",
							"margin-top": "16px",
							"padding-left": "0px",
							"padding-bottom": "5px",
							"padding-right": "0px",
							"padding-top": "5px",
						},
					},
				],
				placeholder: [],
				attrs: { hideOnMobile: false, lock: false, marker: "" },
				style: {
					"background-color": "",
					"background-position": "center center",
					"background-repeat": "no-repeat",
					"background-image": "url()",
					"body-width": 600,
					"content-width": 600,
					"content-background-color": "",
					"content-background-repeat": "no-repeat",
					"content-background-position": "center center",
					"content-background-image": "url()",
					"content-margin-left": "0px",
					"content-margin-bottom": "0px",
					"content-margin-right": "0px",
					"content-margin-top": "0px",
					"content-padding-left": "0px",
					"content-padding-bottom": "0px",
					"content-padding-right": "0px",
					"content-padding-top": "0px",
					"content-border-radius": "0px",
					"content-border-top-color": "#000000",
					"content-border-top-style": "solid",
					"content-border-top-width": "0px",
					"content-border-right-color": "#000000",
					"content-border-right-style": "solid",
					"content-border-right-width": "0px",
					"content-border-bottom-color": "#000000",
					"content-border-bottom-style": "solid",
					"content-border-bottom-width": "0px",
					"content-border-left-color": "#000000",
					"content-border-left-style": "solid",
					"content-border-left-width": "0px",
				},
				customData: {},
			},
			{
				eid: "lTxl2e4so",
				type: "block-level-loop",
				children: [],
				attrs: { lock: false, expression: "dummy_expression" },
				style: {},
			},
			{
				eid: "7MLLGm3yG",
				type: "block-level-conditional",
				children: [
					{
						eid: "tbVWioaPaw",
						type: "branch",
						children: [],
						attrs: { expression: "dummy_expression", type: "if" },
						style: {},
					},
				],
				attrs: { lock: false },
				style: {},
			},
		],
		attrs: {
			usedColors: [
				"#595959",
				"#000000",
				"#cccccc",
				"#cc0000",
				"#FCFCFC",
				"#5555ff",
				"#FDFDFD",
				"#FBFBFB",
				"#999999",
				"#f2f2f2",
				"#ffffff",
			],
		},
		style: {
			"background-color": "#FFFFFF",
			"background-position": "center center",
			"background-repeat": "repeat",
			"background-image": "url()",
			"body-width": 600,
		},
		version: "2.0.0",
	},
	variables: [],
	title: "Imported Document",
	previewText: "",
	subjectLine: "",
};
